#ifndef INC_REGISTERS_H_
#define INC_REGISTERS_H_

// Register map size
#define REGISTER_MAP_SIZE 0x60

// Register addresses
#define REG_MAP_VER_LSB 0x00
#define REG_MAP_VER_MSB 0x01
#define REG_STATUS 0x02
#define REG_RESERVED1 0x03
#define REG_CONTROL 0x04
#define REG_CONTROL2 0x05
#define REG_CONFIG 0x06
#define REG_RESERVED3 0x07

#define REG_RESERVED4 0x08
#define REG_RESERVED5 0x09
#define REG_RESERVED6 0x0A
#define REG_RESERVED7 0x0B
#define REG_RESERVED8 0x0C
#define REG_RESERVED9 0x0D
#define REG_RESERVED10 0x0E
#define REG_RESERVED11 0x0F

#define REG_CONCENTRATION_LLSB 0x10
#define REG_CONCENTRATION_LMSB 0x11
#define REG_CONCENTRATION_MLSB 0x12
#define REG_CONCENTRATION_MMSB 0x13
#define REG_TEMPERATURE_LLSB 0x14
#define REG_TEMPERATURE_LMSB 0x15
#define REG_TEMPERATURE_MLSB 0x16
#define REG_TEMPERATURE_MMSB 0x17

#define REG_HUMIDITY_LLSB 0x18
#define REG_HUMIDITY_LMSB 0x19
#define REG_HUMIDITY_MLSB 0x1A
#define REG_HUMIDITY_MMSB 0x1B
#define REG_RESERVED16 0x1C
#define REG_RESERVED17 0x1D
#define REG_RESERVED18 0x1E
#define REG_RESERVED19 0x1F

#define REG_FRONTEND_ID_LLSB 0x20
#define REG_FRONTEND_ID_LMSB 0x21
#define REG_FRONTEND_ID_MLSB 0x22
#define REG_FRONTEND_ID_MMSB 0x23
#define REG_FIRMWARE_VER_LSB 0x24
#define REG_FIRMWARE_VER_MSB 0x25
#define REG_RESERVED20 0x26
#define REG_RESERVED21 0x27

#define REG_RESERVED22 0x28
#define REG_RESERVED23 0x29
#define REG_RESERVED24 0x2A
#define REG_RESERVED25 0x2B
#define REG_RESERVED26 0x2C
#define REG_RESERVED27 0x2D
#define REG_RESERVED28 0x2E
#define REG_RESERVED29 0x2F

#define REG_CALIBRATION_DATA_INTERCEPT_LLSB 0x30
#define REG_CALIBRATION_DATA_INTERCEPT_LMSB 0x31
#define REG_CALIBRATION_DATA_INTERCEPT_MLSB 0x32
#define REG_CALIBRATION_DATA_INTERCEPT_MMSB 0x33
#define REG_CALIBRATION_DATA_CURRENT_LLSB 0x34
#define REG_CALIBRATION_DATA_CURRENT_LMSB 0x35
#define REG_CALIBRATION_DATA_CURRENT_MLSB 0x36
#define REG_CALIBRATION_DATA_CURRENT_MMSB 0x37

#define REG_CALIBRATION_DATA_HUMIDITY_LLSB 0x38
#define REG_CALIBRATION_DATA_HUMIDITY_LMSB 0x39
#define REG_CALIBRATION_DATA_HUMIDITY_MLSB 0x3A
#define REG_CALIBRATION_DATA_HUMIDITY_MMSB 0x3B
#define REG_CALIBRATION_DATA_TEMPERATURE_LLSB 0x3C
#define REG_CALIBRATION_DATA_TEMPERATURE_LMSB 0x3D
#define REG_CALIBRATION_DATA_TEMPERATURE_MLSB 0x3E
#define REG_CALIBRATION_DATA_TEMPERATURE_MMSB 0x3F

#define REG_CALIBRATION_DATA_INTERCEPT_TEMP_LLSB 0x40
#define REG_CALIBRATION_DATA_INTERCEPT_TEMP_LMSB 0x41
#define REG_CALIBRATION_DATA_INTERCEPT_TEMP_MLSB 0x42
#define REG_CALIBRATION_DATA_INTERCEPT_TEMP_MMSB 0x43
#define REG_CALIBRATION_DATA_CURRENT_TEMP_LLSB 0x44
#define REG_CALIBRATION_DATA_CURRENT_TEMP_LMSB 0x45
#define REG_CALIBRATION_DATA_CURRENT_TEMP_MLSB 0x46
#define REG_CALIBRATION_DATA_CURRENT_TEMP_MMSB 0x47

#define REG_CALIBRATION_DATA_HUMIDITY_TEMP_LLSB 0x48
#define REG_CALIBRATION_DATA_HUMIDITY_TEMP_LMSB 0x49
#define REG_CALIBRATION_DATA_HUMIDITY_TEMP_MLSB 0x4A
#define REG_CALIBRATION_DATA_HUMIDITY_TEMP_MMSB 0x4B
#define REG_CALIBRATION_DATA_TEMPERATURE_TEMP_LLSB 0x4C
#define REG_CALIBRATION_DATA_TEMPERATURE_TEMP_LMSB 0x4D
#define REG_CALIBRATION_DATA_TEMPERATURE_TEMP_MLSB 0x4E
#define REG_CALIBRATION_DATA_TEMPERATURE_TEMP_MMSB 0x4F

#define REG_CONCENTRATION_RAW_SUM_LSB 0x50
#define REG_CONCENTRATION_RAW_SUM_MSB 0x51
#define REG_TEMPERATURE_RAW_SHT40_LSB 0x52
#define REG_TEMPERATURE_RAW_SHT40_MSB 0x53
#define REG_HUMIDITY_RAW_SHT40_LSB 0x54
#define REG_HUMIDITY_RAW_SHT40_MSB 0x55
#define REG_CONCENTRATION_PERCENT_BOUND_LOW 0x56
#define REG_CONCENTRATION_PERCENT_BOUND_HIGH 0x57

#define REG_MEASUREMENTS_COUNTER_LLSB 0x58
#define REG_MEASUREMENTS_COUNTER_LMSB 0x59
#define REG_MEASUREMENTS_COUNTER_MLSB 0x5A
#define REG_MEASUREMENTS_COUNTER_MMSB 0x5B
#define REG_FRONTEND_MODE 0x5C
#define REG_RESERVED33 0x5D
#define REG_RESERVED34 0x5E
#define REG_RESERVED35 0x5F

#define REG_FRONTEND_ID REG_FRONTEND_ID_LLSB
#define REG_CONCENTRATION REG_CONCENTRATION_LLSB
#define REG_TEMPERATURE REG_TEMPERATURE_LLSB
#define REG_HUMIDITY REG_HUMIDITY_LLSB
#define REG_CONCENTRATION_RAW_SUM REG_CONCENTRATION_RAW_SUM_LSB
#define REG_TEMPERATURE_RAW_SHT40 REG_TEMPERATURE_RAW_SHT40_LSB
#define REG_HUMIDITY_RAW_SHT40 REG_HUMIDITY_RAW_SHT40_LSB
#define REG_CALIBRATION_DATA_INTERCEPT REG_CALIBRATION_DATA_INTERCEPT_LLSB
#define REG_CALIBRATION_DATA_CURRENT REG_CALIBRATION_DATA_CURRENT_LLSB
#define REG_CALIBRATION_DATA_HUMIDITY REG_CALIBRATION_DATA_HUMIDITY_LLSB
#define REG_CALIBRATION_DATA_TEMPERATURE REG_CALIBRATION_DATA_TEMPERATURE_LLSB
#define REG_CALIBRATION_DATA_INTERCEPT_TEMP REG_CALIBRATION_DATA_INTERCEPT_TEMP_LLSB
#define REG_CALIBRATION_DATA_CURRENT_TEMP REG_CALIBRATION_DATA_CURRENT_TEMP_LLSB
#define REG_CALIBRATION_DATA_HUMIDITY_TEMP REG_CALIBRATION_DATA_HUMIDITY_TEMP_LLSB
#define REG_CALIBRATION_DATA_TEMPERATURE_TEMP REG_CALIBRATION_DATA_TEMPERATURE_TEMP_LLSB

// Control register bit description
#define REG_CONTROL_START_MEASUREMENT_Pos 0
#define REG_CONTROL_START_MEASUREMENT_Mask (1 << REG_CONTROL_START_MEASUREMENT_Pos)
#define REG_CONTROL_START_MEASUREMENT REG_CONTROL_START_MEASUREMENT_Mask
#define REG_CONTROL_APPLY_CALIBRATION_COEFF_Pos 1
#define REG_CONTROL_APPLY_CALIBRATION_COEFF_Mask (1 << REG_CONTROL_APPLY_CALIBRATION_COEFF_Pos)
#define REG_CONTROL_APPLY_CALIBRATION_COEFF REG_CONTROL_APPLY_CALIBRATION_COEFF_Mask

// Control register bit description
#define REG_CONTROL2_SET_MODE_Pos 0
#define REG_CONTROL2_SET_MODE_Mask (1 << REG_CONTROL2_SET_MODE_Pos)
#define REG_CONTROL2_SET_MODE REG_CONTROL2_SET_MODE_Mask
#define REG_CONTROL2_SET_CONCENTRATION_PERCENT_BOUNDS_Pos 1
#define REG_CONTROL2_SET_CONCENTRATION_PERCENT_BOUNDS_Mask (1 << REG_CONTROL2_SET_CONCENTRATION_PERCENT_BOUNDS_Pos)
#define REG_CONTROL2_SET_CONCENTRATION_PERCENT_BOUNDS REG_CONTROL2_SET_CONCENTRATION_PERCENT_BOUNDS_Mask

// Status register bit description
#define REG_STATUS_MEASUREMENT_FINISHED_Pos 0
#define REG_STATUS_MEASUREMENT_FINISHED_Mask (1 << REG_STATUS_MEASUREMENT_FINISHED_Pos)
#define REG_STATUS_MEASUREMENT_FINISHED REG_STATUS_MEASUREMENT_FINISHED_Mask
#define REG_STATUS_MEASUREMENT_IN_PROGRESS_Pos 1
#define REG_STATUS_MEASUREMENT_IN_PROGRESS_Mask (1 << REG_STATUS_MEASUREMENT_IN_PROGRESS_Pos)
#define REG_STATUS_MEASUREMENT_IN_PROGRESS REG_STATUS_MEASUREMENT_IN_PROGRESS_Mask
#define REG_STATUS_SHT4X_ERROR_Pos 2
#define REG_STATUS_SHT4X_ERROR_Mask (1 << REG_STATUS_SHT4X_ERROR_Pos)
#define REG_STATUS_SHT4X_ERROR REG_STATUS_SHT4X_ERROR_Mask
#define REG_STATUS_MEASUREMENT_ERROR_Pos 3
#define REG_STATUS_MEASUREMENT_ERROR_Mask (1 << REG_STATUS_MEASUREMENT_ERROR_Pos)
#define REG_STATUS_MEASUREMENT_ERROR REG_STATUS_MEASUREMENT_ERROR_Mask

#define CMD_READ 0xAA
#define CMD_WRITE 0x55
#define CMD_NEWLINE 0x0A
#define CMD_SIZE 4
#define CMD_WRITE_ACK_SIZE 2

#endif /* INC_REGISTERS_H_ */
